[2025-03-17T15:29:32.896+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T15:29:32.923+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-13T02:00:00+00:00 [queued]>
[2025-03-17T15:29:32.938+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-13T02:00:00+00:00 [queued]>
[2025-03-17T15:29:32.939+0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T15:29:32.963+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_task> on 2025-03-13 02:00:00+00:00
[2025-03-17T15:29:32.978+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow_rest_api_dag', 'fetch_task', 'scheduled__2025-03-13T02:00:00+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflow_rest_api_open_weather_data.py', '--cfg-path', '/tmp/tmpk489sq8v']
[2025-03-17T15:29:32.980+0600] {standard_task_runner.py:105} INFO - Job 169: Subtask fetch_task
[2025-03-17T15:29:32.985+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22950) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T15:29:32.986+0600] {standard_task_runner.py:72} INFO - Started process 22962 to run task
[2025-03-17T15:29:33.030+0600] {task_command.py:467} INFO - Running <TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-13T02:00:00+00:00 [running]> on host shamim-X541UV
[2025-03-17T15:29:33.122+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_airflow_rest_api_dag' AIRFLOW_CTX_TASK_ID='fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-13T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-13T02:00:00+00:00'
[2025-03-17T15:29:33.123+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T15:29:33.124+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T15:29:33.124+0600] {logging_mixin.py:190} INFO - Current task name:fetch_task state:running start_date:2025-03-17 09:29:32.924022+00:00
[2025-03-17T15:29:33.124+0600] {logging_mixin.py:190} INFO - Dag name:etl_airflow_rest_api_dag and current dag run status:running
[2025-03-17T15:29:33.125+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T15:29:34.268+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/REST_openweatherMap_ETL_AIRFLOW/dags/etl_airflow_rest_api_open_weather_data.py", line 33, in featch_weather_data
    'city': data['name'],
            ~~~~^^^^^^^^
KeyError: 'name'
[2025-03-17T15:29:34.274+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-17T15:29:34.275+0600] {logging_mixin.py:190} INFO - Task start:2025-03-17 09:29:32.924022+00:00 end:2025-03-17 09:29:34.274104+00:00 duration:1.350082
[2025-03-17T15:29:34.275+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_task> dag:<DAG: etl_airflow_rest_api_dag> dagrun:<DagRun etl_airflow_rest_api_dag @ 2025-03-13 02:00:00+00:00: scheduled__2025-03-13T02:00:00+00:00, state:running, queued_at: 2025-03-17 09:29:28.337723+00:00. externally triggered: False>
[2025-03-17T15:29:34.275+0600] {logging_mixin.py:190} INFO - Failure caused by 'name'
[2025-03-17T15:29:34.275+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_airflow_rest_api_dag, task_id=fetch_task, run_id=scheduled__2025-03-13T02:00:00+00:00, execution_date=20250313T020000, start_date=20250317T092932, end_date=20250317T092934
[2025-03-17T15:29:34.741+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T15:29:34.742+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 169 for task fetch_task ('name'; 22962)
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/REST_openweatherMap_ETL_AIRFLOW/dags/etl_airflow_rest_api_open_weather_data.py", line 33, in featch_weather_data
    'city': data['name'],
            ~~~~^^^^^^^^
KeyError: 'name'
[2025-03-17T15:29:34.810+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-17T15:29:34.837+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T15:29:34.973+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
