[2025-03-17T15:27:04.266+0600] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-17T15:27:04.284+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-12T07:00:00+00:00 [queued]>
[2025-03-17T15:27:04.297+0600] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-12T07:00:00+00:00 [queued]>
[2025-03-17T15:27:04.297+0600] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-17T15:27:04.315+0600] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_task> on 2025-03-12 07:00:00+00:00
[2025-03-17T15:27:04.332+0600] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'etl_airflow_rest_api_dag', 'fetch_task', 'scheduled__2025-03-12T07:00:00+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/etl_airflow_rest_api_open_weather_data.py', '--cfg-path', '/tmp/tmps8f0_jeq']
[2025-03-17T15:27:04.333+0600] {standard_task_runner.py:105} INFO - Job 150: Subtask fetch_task
[2025-03-17T15:27:04.342+0600] {logging_mixin.py:190} WARNING - /home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22535) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-17T15:27:04.343+0600] {standard_task_runner.py:72} INFO - Started process 22558 to run task
[2025-03-17T15:27:04.392+0600] {task_command.py:467} INFO - Running <TaskInstance: etl_airflow_rest_api_dag.fetch_task scheduled__2025-03-12T07:00:00+00:00 [running]> on host shamim-X541UV
[2025-03-17T15:27:04.507+0600] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='etl_airflow_rest_api_dag' AIRFLOW_CTX_TASK_ID='fetch_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-12T07:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-12T07:00:00+00:00'
[2025-03-17T15:27:04.510+0600] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-17T15:27:04.510+0600] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-17T15:27:04.511+0600] {logging_mixin.py:190} INFO - Current task name:fetch_task state:running start_date:2025-03-17 09:27:04.285006+00:00
[2025-03-17T15:27:04.511+0600] {logging_mixin.py:190} INFO - Dag name:etl_airflow_rest_api_dag and current dag run status:running
[2025-03-17T15:27:04.512+0600] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-17T15:27:04.683+0600] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/REST_openweatherMap_ETL_AIRFLOW/dags/etl_airflow_rest_api_open_weather_data.py", line 31, in featch_weather_data
    'city': data['name'],
            ~~~~^^^^^^^^
KeyError: 'name'
[2025-03-17T15:27:04.694+0600] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-17T15:27:04.694+0600] {logging_mixin.py:190} INFO - Task start:2025-03-17 09:27:04.285006+00:00 end:2025-03-17 09:27:04.693512+00:00 duration:0.408506
[2025-03-17T15:27:04.695+0600] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_task> dag:<DAG: etl_airflow_rest_api_dag> dagrun:<DagRun etl_airflow_rest_api_dag @ 2025-03-12 07:00:00+00:00: scheduled__2025-03-12T07:00:00+00:00, state:running, queued_at: 2025-03-17 09:26:57.546053+00:00. externally triggered: False>
[2025-03-17T15:27:04.696+0600] {logging_mixin.py:190} INFO - Failure caused by 'name'
[2025-03-17T15:27:04.697+0600] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_airflow_rest_api_dag, task_id=fetch_task, run_id=scheduled__2025-03-12T07:00:00+00:00, execution_date=20250312T070000, start_date=20250317T092704, end_date=20250317T092704
[2025-03-17T15:27:04.717+0600] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-17T15:27:04.718+0600] {standard_task_runner.py:124} ERROR - Failed to execute job 150 for task fetch_task ('name'; 22558)
Traceback (most recent call last):
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/airflow_venv/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shamim/REST_openweatherMap_ETL_AIRFLOW/dags/etl_airflow_rest_api_open_weather_data.py", line 31, in featch_weather_data
    'city': data['name'],
            ~~~~^^^^^^^^
KeyError: 'name'
[2025-03-17T15:27:04.760+0600] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-17T15:27:04.796+0600] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-17T15:27:04.805+0600] {local_task_job_runner.py:245} INFO - ::endgroup::
